### ISSUE TITLE
Data Preprocessing Code

### ISSUE THREAD

**Issue by BalinLin** [hhqweasd/G2R-ShadowNet#1]
Hello, could you provide the code you do the data preprocessing of your training data?
I mean the code that you create training data in "A, B, C, D, E, F" folders.
And I am also wondering if the following correspondence correct?

**folderA** means **R<sub>n</sub>**.
**folderB** means **R<sub>s</sub>**.
**folderC** means **M**.
**folderD** means **S**.
**folderE** means **(S - R<sub>n</sub>)**.
**folderF** means **ψ(M)**.
![figure2](https://user-images.githubusercontent.com/23059007/116861774-40c81d00-ac36-11eb-85b4-67b60e294cd4.png)

Thanks a lot.

**Comment by Teddy12155555** [comment]
亲，我也被这坑给老整死了
咱需要大佬资料前处理的代码，
小弟想知道大佬是如何将三个资料夹处理成ABCDEF六个档案夹的？
可以请您提供呗？
爱你，萌萌哒

**Comment by hhqweasd** [comment]
Sorry for the confusion, I have provided the data processing code ```gettraindata.m```.
The training data can be generated by using the original ISTD dataset and the code ```gettraindata.m``` or download the training data from: GoogleDrive: [ISTD](https://drive.google.com/file/d/1az6HF6VTD6w1AcEFzW4RstAEZgjTqzPB/view?usp=sharing) | BaiduNetdisk: [ISTD](https://pan.baidu.com/s/1TppO4RqehJBh-TEIseYErA) (Access code: 1111)
**train_A** means **Rn**.
**train_B** means **M**.
**train_C** means **S**. (shadow images in the training set of ISTD)
**train_D** means **Rs**.
**train_E** means **(S - Rn)**.
**train_F** means **ψ(M)**.

**Comment by BalinLin** [comment]
Thank you my bro!!
