### ISSUE TITLE
How to get the mask for shadow generation? 

### ISSUE THREAD

**Issue by LoveU3tHousand2** [hhqweasd/G2R-ShadowNet#11]
How to get a valid mask from other data  for shadow generation, your paper saids only "1 - a < Area(Rn)/Area(Rs) < 1 + a" and "Rs cover more than 1/2 randomly ..." but there is no code for that.

Can you offer that or give some suggestion ?

**Comment by hhqweasd** [comment]
Please refer to this [code](https://github.com/hhqweasd/G2R-ShadowNet/blob/main/gettraindata.m).
