### ISSUE TITLE
关于AISTD数据集：大家可以搜索关于“Shadow Removal via Shadow Image Decomposition”这篇文章的github，里面有AISTD数据集的下载链接

### ISSUE THREAD

**Issue by DoraemonPockets** [hhqweasd/G2R-ShadowNet#13]
> Yes, Please use AISTD dataset

you mean evaluation use the AISTD dataset? where I can got the AISTD dataset? I can not find it, thanks.

_Originally posted by @neverstoplearn in https://github.com/hhqweasd/G2R-ShadowNet/issues/6#issuecomment-1590517866_

**Comment by neverstoplearn** [comment]
> ```
>           > Yes, Please use AISTD dataset
> ```
> 
> you mean evaluation use the AISTD dataset? where I can got the AISTD dataset? I can not find it, thanks.
> 
> _Originally posted by @neverstoplearn in [#6 (comment)](https://github.com/hhqweasd/G2R-ShadowNet/issues/6#issuecomment-1590517866)_
感谢，我试一下。

**Comment by neverstoplearn** [comment]
> ```
>           > Yes, Please use AISTD dataset
> ```
> 
> you mean evaluation use the AISTD dataset? where I can got the AISTD dataset? I can not find it, thanks.
> 
> _Originally posted by @neverstoplearn in [#6 (comment)](https://github.com/hhqweasd/G2R-ShadowNet/issues/6#issuecomment-1590517866)_

我下载了AISTD数据集，
maskdir = 'test_mask'（作者提供的test_mask）
shadowdir = 'AISTD' (作者提供的模型结果)  
freedir = 'test_C_fixed_official'(AISTD数据集)
最终得到结果：
PSNR(all,non-shadow,shadow):
30.522497	37.589435	32.146250
SSIM(all,non-shadow,shadow):
0.000000	0.000000	0.000000
PI-Lab(all,non-shadow,shadow):
3.862418	2.369646	10.006975
PP-Lab(all,non-shadow,shadow):
3.862418	2.325859	10.681674
请问我数据选择得有问题吗？谢谢。

**Comment by DoraemonPockets** [comment]
我在跑结果的时候shadowdir就是模型最后生成的去除阴影的结果图片，输出SSIM的那一段代码被注释掉了，你把前面的%去掉就可以得到SSIM了

**Comment by neverstoplearn** [comment]
> 我在跑结果的时候shadowdir就是模型最后生成的去除阴影的结果图片，输出SSIM的那一段代码被注释掉了，你把前面的%去掉就可以得到SSIM了 已经解决了

**Comment by Jasonshao0123** [comment]
请教下从哪里可以得出RMSE的指标结果呢？
