### ISSUE TITLE
去阴影的网络结构

### ISSUE THREAD

**Issue by BaiCHao12** [hhqweasd/G2R-ShadowNet#14]
去阴影的网络结构为什么需要输入mask，如果在去阴影的时候需要同时输入阴影mask，代码的网络结构中有没有看到”阴影掩码网络“结构

**Comment by hhqweasd** [comment]
输入mask阴影去除效果更好，在train.py用过mask：output=netG_2(fake_nsr+real_nsrs,mask*2.0-1.0)
