### ISSUE TITLE
ISTD Results

### ISSUE THREAD

**Issue by yx-chan131** [hhqweasd/G2R-ShadowNet#6]
Hi, I run the evaluation code provided in this repo (evaluate.m) with the following settings:
maskdir - original ISTD mask (test_B)
shadowdir - Results of G2R-ShadowNet downloaded from this repo
freedir - original ISTD groundtruth (test_C)

![istd_result](https://user-images.githubusercontent.com/68681893/136744854-aa57a64c-be0d-426e-8b30-dcabc76f09b6.JPG)
But the result I get is nowhere near the result in the paper nor on this Github repo README page. 
Looking forward to hearing from you! Thanks!

**Comment by zysxmu** [comment]
Do you solve this problem?

**Comment by zysxmu** [comment]
It should be AISDT

**Comment by DoraemonPockets** [comment]
I have the same question，Do you solve this problem?

**Comment by zysxmu** [comment]
Yes, Please use AISTD dataset

**Comment by neverstoplearn** [comment]
> Yes, Please use AISTD dataset

you mean evaluation use the AISTD dataset? where I can got the AISTD dataset? I can not find it, thanks.

**Comment by neverstoplearn** [comment]
> It should be AISDT

can you show me how to choose maskdir shadowdir freedir, thanks.

**Comment by DoraemonPockets** [comment]
> > Yes, Please use AISTD dataset
> 
> you mean evaluation use the AISTD dataset? where I can got the AISTD dataset? I can not find it, thanks.
搜索“Shadow Removal via Shadow Image Decomposition”这篇文章的github，里面有下载链接
